#pragma once

#ifdef VIA_ENABLE
#   define DYNAMIC_KEYMAP_LAYER_COUNT 4
#endif

#ifndef __arm__
#   define NO_ACTION_ONESHOT
#endif

#ifdef POINTING_DEVICE_ENABLE
#   define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_ENABLE
#   define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_TIMEOUT_MS 1000
#   define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_THRESHOLD 8
#else
#   define DRGSCRL KC_NO
#   define DPI_MOD KC_NO
#   define S_D_MOD KC_NO
#   define SNIPING KC_NO
#endif

#define CHARYBDIS_AUTO_SNIPING_ON_LAYER LAYER_POINTER
